### ISSUE TITLE
fix: platform test are not displaying text.

### ISSUE THREAD

**Issue by hawkbee1** [Betterment/alchemist#39] opened 2022-03-29 18:57 UTC
On my locals, when running the example test on fresh install (flutter create or very_good create), the linux and macos goldens don't display text.
![image](https://user-images.githubusercontent.com/49282360/160682029-88cbea90-2495-449f-a530-1f1db98d0b2a.png)
The CI font is not used because the result is different if you look at the icon and the spaces.
![image](https://user-images.githubusercontent.com/49282360/160682232-9428cfe1-2692-4990-af37-b6daf4305050.png)

the result should be:
![image](https://user-images.githubusercontent.com/49282360/160682446-83e3838b-15c6-4c9e-a243-df6e82367625.png)

I tried different PlatformGoldensConfig with no success.
**Adding Roboto fonts from alchemist package into the project is solving the issue.**

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 21.10 5.13.0-37-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by mrgnhnt96** [comment] 2022-03-29 22:19
Is there an ETA for a fix for this?

> Adding Roboto fonts from alchemist package into the project is solving the issue.

Also, how can this be done in the meantime?

**Comment by Giuspepe** [comment] 2022-04-02 00:18
@mrgnhnt96 You can use the `loadAppFonts` function from `golden_toolkit` until `alchemist` supports this as well. Then text should be rendered in the platform goldens as well.

```dart
import 'package:alchemist/alchemist.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:golden_toolkit/golden_toolkit.dart' show loadAppFonts;

void main() {
  setUpAll(() async {
    // this is the relevant line of code
    await loadAppFonts();
  });

  group('ListTile Golden Tests', () {
    goldenTest(
      'renders correctly',
      fileName: 'alchemist_sample',
      constraints: const BoxConstraints(maxWidth: 600),
      builder: () => GoldenTestGroup(
        columnWidthBuilder: (_) => const FlexColumnWidth(),
        children: [
          GoldenTestScenario(
            name: 'with title',
            child: const ListTile(
              title: Text('ListTile.title'),
            ),
          ),
          GoldenTestScenario(
            name: 'with title and subtitle',
            child: const ListTile(
              title: Text('ListTile.title'),
              subtitle: Text('ListTile.subtitle'),
            ),
          ),
          GoldenTestScenario(
            name: 'with trailing icon',
            child: const ListTile(
              title: Text('ListTile.title'),
              trailing: Icon(Icons.chevron_right_rounded),
            ),
          ),
        ],
      ),
    );
  });
}

```

**Comment by mrgnhnt96** [comment] 2022-04-05 16:23
> You can use the loadAppFonts function from golden_toolkit until alchemist supports this as well. Then text should be rendered in the platform goldens as well.

Thank you! This made it work for me. 👍
Looking forward to removing it when the works out of the box 😎

**Comment by jeroen-meijer** [comment] 2022-06-02 12:36
This is fixed by #55 I believe.

Closing this. If it still occurs, feel free to ask to reopen, or open another ticket. Thanks!

**Comment by TesteurManiak** [comment] 2022-07-18 20:44
Well it seems like the problem is still occuring, I had to write a small utility function to load the Roboto font:

```dart
/// This method is used to load the default Roboto font family from the
/// alchemist package.
Future<void> loadDefaultTestFont() async {
  TestWidgetsFlutterBinding.ensureInitialized();

  const robotoPath = 'assets/fonts/Roboto';
  await _loadFamily(
    package: 'alchemist',
    name: 'Roboto',
    assets: [
      '$robotoPath/Roboto-Black.ttf',
      '$robotoPath/Roboto-Bold.ttf',
      '$robotoPath/Roboto-Light.ttf',
      '$robotoPath/Roboto-Medium.ttf',
      '$robotoPath/Roboto-Regular.ttf',
      '$robotoPath/Roboto-Thin.ttf',
    ],
  );
}

Future<void> _loadFamily({
  required String package,
  required String name,
  required List<String> assets,
}) async {
  final prefix = 'packages/$package/';
  final fontLoader = FontLoader(name);

  for (final asset in assets) {
    final bytes = rootBundle.load('$prefix$asset');
    fontLoader.addFont(bytes);
  }
  await fontLoader.load();
}
```

Then you have to call `loadDefaultTestFont()` in the `flutter_test_config.dart`:

```dart
Future<void> testExecutable(FutureOr<void> Function() testMain) async {
 // ...

  await loadDefaultTestFont();

  // ...
}
```
![text_styles](https://user-images.githubusercontent.com/14369698/179614119-d634db80-99b7-47bb-85c1-b7ffd27a700c.png)

**Comment by renefloor** [comment] 2022-08-01 08:20
@jeroen-meijer You've solved this by stripping away the package name of the font. However, this assume the package is provided by the flutter project where the snapshot is being made. However, in our setup we have 2 different theme packages that provide their font. The main package runs snapshot tests using both theme packages, but the fonts cannot be found because the package name is removed from it.

**Comment by jeroen-meijer** [comment] 2022-08-01 09:47
@TesteurManiak @renefloor Thanks for the info, both of you :)

Pinging @Kirpal, you had experience with font asset loading IIRC, and might have more context on this than I do. If not, feel free to pass it back to me and I'll have a look.

I'll reopen this issue.

@renefloor, does a workaround like @TesteurManiak's work in the meantime? Perhaps you could add the setup in your Flutter test setup file.

**Comment by meg4cyberc4t** [comment] 2023-09-25 08:31
Hello. I seem to have this problem repeated.
I am running tests with the **Inter** font family, which I connect via pubspec.yaml (ttf files). Use alchemist with version 0.7.0 for this.
As a result, CI tests:
![auth_sign_in_screen_widget](https://github.com/Betterment/alchemist/assets/66907532/03612d9d-d8d4-4c05-ae4d-9db62cb9cfed)
and macos platform tests:
![auth_sign_in_screen_widget](https://github.com/Betterment/alchemist/assets/66907532/29200ff2-2db2-4241-b680-ec73ac867ab6)

As you can see, the font is replaced with squares, and not the Ahem font. I suspect the problem is downloading fonts and the solutions you have already given didn't help me.

**Comment by btrautmann** [comment] 2024-09-16 19:27
I believeeeee this should be fixed by https://github.com/Betterment/alchemist/pull/111. Please re-open if that's not the case.

**Closed by btrautmann** 2024-09-16 19:27 UTC
Labels: bug

**Comment by renefloor** [comment] 2024-11-08 15:09
Hi @btrautmann. It indeed works as expected now, thanks!
